- name: play 1
  hosts: web
  vars_prompt:
  - name: name
    prompt: " please enter the name of the candidate "
    private: false
  tasks:
  - name: apply the varaibles
    vars: 
      name: "bharath"
    debug:
      msg: " my self {{name}} and i have studied my btech in mech "
  - name : again testing 
    debug:
      msg: " my self {{name}} and i have studied my engg in mech"