- name: play 1
  hosts: web
  vars_prompt:
    names: name
    prompt: " please enter the name of the candidate "
  tasks:
  - name: apply the varaibles
    vars: 
      name: "bharath"
    debug:
      msg: " my self {{name}} and i have studied my {{study}} in {{stream}} "
  - name : again testing 
    debug:
      msg: " my self {{name}} and i have studied my {{study}} in {{stream}} "