- name: checking user exist or not
  hosts: web
  become: yes
  tasks:
  - name: user checking
    command: id expense
    register: user
    ignore_errors: true
  - name: print user information
     ansible.builtin.debug:
       msg: "User info: {{user}}"  
  - name: user existancy checking
    command: useradd expense
    when: user.rc != 0 
  - name : printing Hello
    debug:
      msg: "print hello "

