- name: user checking with condition
  hosts: localhost
  become: yes
  tasks:
  - name: user checking in server
    command: id srinu
    register: user
    ignore_errors: true
  - name: printing user srinu data
    debug:
      msg: "print{{user}}"
  - name: if user not present adding user
    command: useradd srinu
    when: user != 0
  - name : printing some thing for clarity
    debug:
      msg: " hii srinu"


